#include "M5Atom.h"
#include "alphabet.h"

Alphabet screen;

void setup()
{
  M5.begin(true, false, true);
  delay(200);
}

void loop()
{
  screen.display(EMPTY,0xffffff);
  delay(200);
  screen.display(FULL,0x888888);
  delay(200);
  screen.display(MARU,0x00ff00);
  delay(200);
  screen.display(BATSU,0xff0000),
  delay(200);
  screen.set_color(0x0000ff);
  screen.display(UP);
  delay(200);
  screen.display(DOWN);
  delay(200);
  screen.display(LEFT);
  delay(200);
  screen.display(RIGHT);
  delay(200);
  screen.display(WIFI_FAILURE);
  delay(200);
  screen.display(WIFI_CONNECTING_1);
  delay(200);
  screen.display(WIFI_CONNECTING_2);
  delay(200);
  screen.display(WIFI_CONNECTING_3);
  delay(200);
  screen.display(WIFI_CONNECTED);
  delay(200);
  screen.display(DJI_D);
  delay(200);
  screen.display(DJI_J);
  delay(200);
  screen.display(DJI_I);
  delay(200);
  screen.display(DJI);
  delay(200);
  screen.display(BT);
  delay(200);
  screen.display(ROS);
  delay(200);
  screen.display(micro_ROS);
  delay(200);
  screen.display(TokyoTech);
  delay(200);
  screen.set_color(0x7272ff);
  screen.display('A');
  delay(200);
  screen.display('B');
  delay(200);
  screen.display('C');
  delay(200);
  screen.display('D');
  delay(200);
  screen.display('E');
  delay(200);
  screen.display('F');
  delay(200);
  screen.display('G');
  delay(200);
  screen.display('H');
  delay(200);
  screen.display('I');
  delay(200);
  screen.display('J');
  delay(200);
  screen.display('K');
  delay(200);
  screen.display('L');
  delay(200);
  screen.display('M');
  delay(200);
  screen.display('N');
  delay(200);
  screen.display('O');
  delay(200);
  screen.display('P');
  delay(200);
  screen.display('Q');
  delay(200);
  screen.display('R');
  delay(200);
  screen.display('S');
  delay(200);
  screen.display('T');
  delay(200);
  screen.display('U');
  delay(200);
  screen.display('V');
  delay(200);
  screen.display('W');
  delay(200);
  screen.display('X');
  delay(200);
  screen.display('Y');
  delay(200);
  screen.display('Z');
  delay(200);
}